api_platform:
    title: 'INSEE City API'
    description: 'Symfony/API Platform API exposing French city data from the INSEE API'
    version: '1.0.0'

    enable_swagger_ui: true
    enable_re_doc: false
    enable_docs: true

    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']

    error_formats:
        jsonproblem: ['application/problem+json']
        jsonld: ['application/ld+json']
        json: ['application/json']

    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']

    swagger:
        versions: [3]

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true

    collection:
        pagination:
            enabled: true

    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'

when@prod:
    api_platform:
        enable_swagger_ui: false
        enable_docs: false
